# These are supported funding model platforms

facebook: ['https://facebook.com/people/Sujay-Mukherjee/100092647425033']
instagram: ['https://instagram.com/devsujay19']
twitter: ['https://twitter.com/devsujay19']
replit: ['https://replit.com/@devsujay19']
